### ISSUE TITLE
problem in install tensorlayer

### ISSUE THREAD

**Issue by Sakura-Luna** [tensorlayer/tensorlayer#1034]
I used the anaconda environment to install tensorlayer using pip, so it removed the updated scikit-learn 0.21.2 and requests 2.22.0. The latter is the basic dependency of anaconda, it should not be re-installed (use pip), which creates trouble for me.
I can't install requests with the conda command.

**Comment by Sakura-Luna** [comment]
Now I can't install any package using conda, because the request will be installed when using conda installation. If there is no request, it will go wrong. If you use pip install requests, the installation will fail. My conda environment is abolished.


RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.

**Comment by Officium** [comment]
I can not reproduce with the last version of miniconda. 
The following code may reinstall requests.
```python
from pip._internal import main
main(['install', 'requests'])
```

**Comment by ChrisWu1997** [comment]
Hi, @Sakura-Luna 

I'm using anaconda and there should be no problem to install tensorlayer using pip under anaconda a environment. Try:
```bash
conda create -n tl2 python==3.6
conda activate tl2
pip install tensorflow==2.0.0-beta
pip install tensorlayer
```
My anaconda version is `4.5.4`.

**Comment by Sakura-Luna** [comment]
@Officium @ChrisWu1997 I don't think you understand what I mean. I am using miniconda. If you want to reproduce this problem, you must install tensorlayer in the base environment. Before that, you need to make sure that the requests version of conda is higher than the version required by tensorlayer. This is the reason why pip uninstall the requests.

**Comment by Officium** [comment]
@Sakura-Luna 
Here are my reproduction steps:
1. remove conda by `rm -rdf ~/miniconda3`
2. install the newest miniconda by `sh Miniconda3-latest-MacOSX-x86_64.sh` without auto init
3. activate the base environment by `. ~/miniconda3/bin/activate`
4. update requests by `pip install requests --upgrade && conda update requests`. The version of requests installed is 2.22.0
5. install tensorlayer by `pip install tensorlayer`. The requests==2.21.0 is installed. The tail of output log is 
```
Installing collected packages: numpy, scipy, joblib, scikit-learn, h5py, pillow, imageio, cycler, kiwisolver, pyparsing, python-dateutil, matplotlib, decorator, networkx, PyWavelets, scikit-image, wrapt, cloudpickle, python-utils, progressbar2, requests, tensorlayer
  Found existing installation: requests 2.22.0
    Uninstalling requests-2.22.0:
      Successfully uninstalled requests-2.22.0
Successfully installed PyWavelets-1.0.3 cloudpickle-1.2.1 cycler-0.10.0 decorator-4.4.0 h5py-2.9.0 imageio-2.5.0 joblib-0.13.2 kiwisolver-1.1.0 matplotlib-3.1.1 networkx-2.3 numpy-1.16.4 pillow-6.1.0 progressbar2-3.39.3 pyparsing-2.4.2 python-dateutil-2.8.0 python-utils-2.3.0 requests-2.21.0 scikit-image-0.15.0 scikit-learn-0.21.0 scipy-1.2.1 tensorlayer-2.1.0 wrapt-1.11.1
```
6. Both `conda install numpy` and `pip install requests --upgrade` are work in a new shell session.

As you mentioned, conda goes wrong because requests is uninstalled and all internet needed conda operation do not work, is it right? 

The solution above is for reinstalling the requests. Another without requests solution for reinstalling requests is to download whl file from the website and then execute `pip install ****.whl`.

**Comment by Sakura-Luna** [comment]
@Officium I am using a recent miniconda version on Windows, where conda install will fail once the requests are uninstalled. Even after using pip to install the request, the use of conda install will cause a RemoveError. I can solve this problem, but I want to say that tensorlayer should not specify a specific version of requests, at least should provide a warning to avoid problems.
Saying a digression. Why can't tensorlayer.rotation set the center of rotation?
