### ISSUE TITLE
Use logging instead of print statements

### ISSUE THREAD

**Issue by mitar** [tensorlayer/tensorlayer#207]
Code is full of [print statements](https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/utils.py#L108). Please use [logging](https://docs.python.org/3/library/logging.html) so that one can intercept output and control noisiness.

**Comment by haiy** [comment]
+1

**Comment by haiy** [comment]
print is dirty for production.

**Comment by zsdonghao** [comment]
Hi, to disable the printing, you can use:

```python
>>> print("You can see me")
>>> with tl.ops.suppress_stdout():
>>>     print("You can't see me")
>>> print("You can see me")
```

**Comment by haiy** [comment]
hi @zsdonghao. it's not about how to suppress print, it's about logging info with more control.If we use logging, then we can config what and where to output .When we want to deploy tl to production environment as service, we need  it to log the normal and exception messages.Besides we found some globals defined in [layers.py]
(https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/layers.py)

```python
set_keep = globals()
set_keep['_layers_name_list'] =[]
set_keep['name_reuse'] = False

```
,this piece of code make tl hard to deploy as service for multiple users.

**Comment by mitar** [comment]
I second everything @haiy said. Both of those two pieces have bitten us as well.

**Comment by zsdonghao** [comment]
@haiy For production, as I know, people usually use [TensorFlow Serving](https://www.tensorflow.org/serving/), threading is not necessary. May be I didn't get you point? or there are some reason threading is better?

**Comment by mitar** [comment]
Sometimes it is just under you. [See here](https://github.com/ray-project/ray/issues/824#issuecomment-322361367).

**Comment by zsdonghao** [comment]
@mitar Thanks, I will think about it carefully ~

**Comment by tomtung** [comment]
Totally agree with the concerns over using print instead of logging. Things like `suppress_stdout` and `disable_print` suppresses stdout globally regardless of whether the prints are from the library, which feels quite overreaching. Logging seems to be more suitable here; see [When to use logging](https://docs.python.org/3/howto/logging.html#when-to-use-logging).

I think we could just add the following to all the modules that needs logging (to create a [logger hierarchy](https://docs.python.org/3/library/logging.html#logger-objects)):
```py
import logging
logger = logging.getLogger(__name__)
```
And use `logger.{debug, info, warning, ...}` instead of `print`, giving users full control over how and the logs are written.

**Comment by tomtung** [comment]
Also not sure why we need global variables to prevent layer name collisions, since after all the use of TensorFlow's variable scopes already handles that.

Maybe it's also easier to just pass `reuse` as a parameter to the constructors of layers, instead of maintaining it as the global state `set_keep['name_reuse']`, which is almost not respected anywhere (except for `TimeDistributedLayer`) anyways.

**Comment by luomai** [comment]
@tomtung @mitar @haiy we are preparing for a PR to replace all the print with logging in the library.

**Comment by DEKHTIARJonathan** [comment]
Just to repeat what I proposed in #306 

The idea would be to make this output optional (default = True or False). I think there could be different ways to do this.

##### 1. Solution - Create a **verbose** parameter in the Layer API
Simple and backward compatible, a "verbose" parameter can be added to the Layer Class and influence the behavior of [print_params()](https://github.com/tensorlayer/tensorlayer/blob/master/tensorlayer/layers.py#L321) method.

##### 2. Use the Logging module from TF.

Why should we re-invent the wheel ? Everything is already implemented in Tensorflow.
We can use the logging level already existing in TF.

```python
tf.logging._level_names    ## outputs => {50: 'FATAL', 40: 'ERROR', 30: 'WARN', 20: 'INFO', 10: 'DEBUG'}
tf.logging.get_verbosity() ## outputs => 30 (default value)

tf.logging.set_verbosity(tf.logging.DEBUG)
tf.logging.get_verbosity() ## outputs => 10
```

We could for instance determine that for logging level <= 20 (INFO & DEBUG), we normally output the Tensorlayer informations, and we don't perform this action for any higher value.
